---
title: "Data Prep"
output: html_notebook
---

## packages

```{r}
pacman::p_load(tidyverse, haven, psych, sjPlot, ggpubr, ggthemes)
```

## data

```{r}
trolley <- read_spss("data/TrolleyExperimentArgumentNew.sav") %>% 
  janitor::clean_names(.) %>% 
  filter(general_finisher == 1) %>% 
  drop_na(t1_eqp_eqp1, t1_eqp_eqp3, t1_eqp_eqp7, t1_eqp_eqp8, t1_eqp_eqp9,
         t1_eqp_eqp11, t1_eqp_eqp12 ,t1_eqp_eqp13, t1_eqp_eqp14, t1_eqp_eqp18,
         t1_eqp_eqp2, t1_eqp_eqp4, t1_eqp_eqp5, t1_eqp_eqp6, t1_eqp_eqp10,
         t1_eqp_eqp15, t1_eqp_eqp16 ,t1_eqp_eqp17, t1_eqp_eqp19, t1_eqp_eqp20,
         t1_szenario1q2, t2_szenario1q2, t1_szenario2q2, t2_szenario2q2) %>% 
  filter(t2_gender != 2) %>% 
  mutate(gender = ifelse(t2_gender == 1, 0, 1)) %>% 
  mutate(leftright = t2_pol_alignment) %>% 
  mutate(pol_interest = 5 - t2_pol_interest) %>% 
  mutate(church_attendance = 7 - t2_religion_church) %>% 
  mutate(age = 2018 - as.numeric(t2_year_of_birth)) %>% 
  mutate(university = ifelse(t2_university == 4, 0, 1))

# trolley %>% 
#   select(general_finisher:t2_religion_community, t2_religion_practice:t2_year_of_birth)


eqp <- trolley %>% 
  select(contains("eqp")) %>% 
#  na.omit() %>% 
  select(t1_eqp_eqp1, t1_eqp_eqp3, t1_eqp_eqp7, t1_eqp_eqp8, t1_eqp_eqp9,
         t1_eqp_eqp11, t1_eqp_eqp12 ,t1_eqp_eqp13, t1_eqp_eqp14, t1_eqp_eqp18,
         t1_eqp_eqp2, t1_eqp_eqp4, t1_eqp_eqp5, t1_eqp_eqp6, t1_eqp_eqp10,
         t1_eqp_eqp15, t1_eqp_eqp16 ,t1_eqp_eqp17, t1_eqp_eqp19, t1_eqp_eqp20)


trolley %>% 
  select(t1_szenario2q2) %>% 
  ggplot(aes(t1_szenario2q2)) +
  geom_histogram()

trolley %>% 
  select(t2_szenario2q2) %>% 
  ggplot(aes(t2_szenario2q2)) +
  geom_histogram()

trolley %>% mutate_all(sjmisc::to_label)
trolley
```


## heatmap

```{r}
ggheatmap <- function(.data) {
  
 library(reshape2)
 
 cormat <- round(cor(.data, use = "pairwise.complete.obs"),3)
 
 # Get upper triangle of the correlation matrix
 get_upper_tri <- function(cormat){
     cormat[lower.tri(cormat)] <- NA
     return(cormat)
   }
 
 reorder_cormat <- function(cormat){
 # Use correlation between variables as distance
 dd <- as.dist((1-cormat)/2)
 hc <- hclust(dd)
 cormat <- cormat[hc$order, hc$order]
 }
 
 # Reorder the correlation matrix
 #cormat <- reorder_cormat(cormat)
 upper_tri <- get_upper_tri(cormat)
 # Melt the correlation matrix
 melted_cormat <- melt(upper_tri, na.rm = TRUE) %>% 
   mutate(value = sprintf('%.2f', value, 2)) %>% 
   mutate(value = as.numeric(value))
 # Create a ggheatmap
 ggplot(melted_cormat, aes(Var2, Var1, fill = value)) +
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
     name="Pearson Correlation\n") +
  ggthemes::theme_hc()+ # minimal theme
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
     size = 12, hjust = 1))+
 # coord_fixed()  + 
 geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
 theme(
   axis.title.x = element_blank(),
   axis.title.y = element_blank(),
   panel.grid.major = element_blank(),
   panel.border = element_blank(),
   panel.background = element_blank(),
   axis.ticks = element_blank(),
   legend.justification = c(1, 0),
   legend.position = c(0.7, 0.8),
   legend.title = element_text(size = 20),
   axis.ticks.length = unit(2, "cm"),
   legend.direction = "horizontal")+
   guides(fill = guide_colorbar(barwidth = 30, barheight = 1.5,
                 title.position = "top", title.hjust = 0.5))
}

ggheatmap(trolley %>% select_if(is.numeric))

ggsave(filename = "images/heatmap2.png", height = 30, width = 30)


# reg_dat %>% 
  # select(t2_gender) %>% table()

```


## factor analysis


```{r}
reg_dat <- eqp %>% 
  psych::pca(2, rotate = "none") %>% 
  predict.psych(data = eqp) %>% 
  cbind(trolley, .)

reg_dat <- reg_dat %>% 
  rename(akquisenz_pca = PC1) %>% 
  rename(ideal_relativ_pca = PC2)  

reg_dat <- eqp %>% 
  psych::pca(2, rotate = "varimax") %>% 
  predict.psych(data = eqp) %>% 
  cbind(reg_dat, .)
  
reg_dat <- reg_dat %>% 
  rename(idealism_pca = RC1) %>% 
  rename(relativism_pca = RC2)   


```

## four types

```{r}
range01 <- function(x, ...){(x - min(x, ...)) / (max(x, ...) - min(x, ...))}

reg_dat %>% 
  mutate_at(vars(relativism_pca, idealism_pca), ~range01(., na.rm=T)) %>% 
  mutate(types = case_when(
    idealism_pca >= .5 & relativism_pca < .5 ~ "Absolutists",
    idealism_pca >= .5 & relativism_pca >= .5 ~ "Situationists",
    idealism_pca < .5 & relativism_pca >= .5 ~ "Subjectivists",
    idealism_pca < .5 & relativism_pca < .5 ~ "Exceptionists"
  )) %>% dplyr::select(types) %>% table()
  
reg_dat %>% 
  ggplot(aes(relativism_pca, idealism_pca)) +
  geom_point(aes(color = types)) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  ggtitle("4 Types of Ethical Positions") +
  geom_smooth(method = "lm")
  
ggsave(filename = "images/four_types.png", height = 8, width = 8)


reg_dat %>% 
  select(types, t1_szenario1q2, t2_szenario1q2) %>% 
  rename(t1 = t1_szenario1q2, t2 = t2_szenario1q2) %>% 
  gather(key, value, -types) %>% 
  ggplot(aes(key, value)) +
  geom_violin(aes(fill = types), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  facet_wrap(~types, nrow = 1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  ggtitle("Opinion Change by four Types of Ethical Positions") +
  xlab("") +
  ylab("Morally justifiable: Switch Track") 


ggsave(filename = "images/Opinionchange_fourtypes.png", height = 5, width = 12)



reg_dat %>% 
  select(types, general_group_control:general_group_information, t1_szenario1q2, t2_szenario1q2) %>% 
  rename(t1 = t1_szenario1q2, t2 = t2_szenario1q2) %>% 
  rename(`Control Group` = general_group_control,
         `Discussion Group` = general_group_discussion,
         `Information Group` = general_group_information
         ) %>% 
  gather(key, value, -types, -t1, -t2) %>% 
  filter(value == 1) %>% 
  mutate(change = t2 - t1)  %>% 
  ggplot(aes(types, change)) +
  geom_violin(aes(fill = types), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  facet_wrap(~key, nrow = 1)  +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_gdocs() +
  ggtitle("Average Opinion Change by four Types of Ethical Positions - Switch Track") +
  xlab("") +
  ylab("Morally justifiable: Switch Track") 

ggsave(filename = "images/Opinionchange_switchtrack2.png", height = 5, width = 12)



reg_dat %>% 
  select(types, general_group_control:general_group_information, t1_szenario2q2, t2_szenario2q2) %>% 
  rename(t1 = t1_szenario2q2, t2 = t2_szenario2q2) %>% 
  rename(`Control Group` = general_group_control,
         `Discussion Group` = general_group_discussion,
         `Information Group` = general_group_information
         ) %>% 
  gather(key, value, -types, -t1, -t2) %>% 
  filter(value == 1) %>% 
  mutate(change = t2 - t1)  %>% 
  ggplot(aes(types, change)) +
  geom_violin(aes(fill = types), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  facet_wrap(~key, nrow = 1)  +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_gdocs() +
  ggtitle("Average Opinion Change by four Types of Ethical Positions - Push Person") +
  xlab("") +
  ylab("Morally justifiable: Push Person") 

ggsave(filename = "images/Opinionchange_pushperson2.png", height = 5, width = 12)



reg_dat %>% 
  select(types, general_group_control:general_group_information, t1_szenario1q2, t2_szenario1q2) %>% 
  rename(t1 = t1_szenario1q2, t2 = t2_szenario1q2) %>% 
  rename(`Control Group` = general_group_control,
         `Discussion Group` = general_group_discussion,
         `Information Group` = general_group_information
         ) %>% 
  gather(key, value, -types, -t1, -t2) %>% 
  filter(value == 1) %>% 
  mutate(change = t2 - t1) %>% #select(types, key) %>% table()
  group_by(types, key) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(types, change)) +
  geom_bar(stat = "identity", aes(fill = types), legend = FALSE) +
  facet_wrap(~key, nrow = 1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_gdocs()  +
  ggtitle("Average Opinion Change by four Types of Ethical Positions - Switch Track") +
  xlab("") +
  ylab("Morally justifiable: Switch Track") 

ggsave(filename = "images/Opinionchange_switchtrack.png", height = 5, width = 12)

reg_dat %>% 
  select(types, general_group_control:general_group_information, t1_szenario2q2, t2_szenario2q2) %>% 
  rename(t1 = t1_szenario2q2, t2 = t2_szenario2q2) %>% 
  rename(`Control Group` = general_group_control,
         `Discussion Group` = general_group_discussion,
         `Information Group` = general_group_information
         ) %>% 
  gather(key, value, -types, -t1, -t2) %>% 
  filter(value == 1) %>% 
  mutate(change = t2 - t1) %>% #select(types, key) %>% table()
  group_by(types, key) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(types, change)) +
  geom_bar(stat = "identity", aes(fill = types), legend = FALSE) +
  facet_wrap(~key, nrow = 1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_gdocs()  +
  ggtitle("Average Opinion Change by four Types of Ethical Positions - Push Person") +
  xlab("") +
  ylab("Morally justifiable: Push Person") 

ggsave(filename = "images/Opinionchange_pushperson.png", height = 5, width = 12)



```

## polarization - negative-binomial

```{r}
nb_dat <- reg_dat %>% 
  #select(idealism_pca, relativism_pca) %>% 
  mutate(ideal_xtremes = ifelse(idealism_pca >= 0.9, 1, 0))  %>% 
  mutate(relative_xtremes = ifelse(relativism_pca >= 0.9, 1, 0)) %>% 
#  select(ideal_xtremes, relative_xtremes) %>% table()
  mutate(absolute_change = abs(t2_szenario1q2 - t1_szenario1q2)) %>% 
  mutate(change_dummy = ifelse(absolute_change > 0, 1 ,0))


pacman::p_load(MASS)

mnb <- glm.nb(absolute_change ~ ideal_xtremes + relative_xtremes + general_group_discussion + ideal_xtremes*general_group_information + gender + leftright + pol_interest + church_attendance + age + university, data = nb_dat)

summary(mnb)

sjPlot::plot_model(mnb, type = "int")

hist(nb_dat$absolute_change)


glm_fit <- glm(change_dummy ~ ideal_xtremes + relative_xtremes + general_group_discussion + general_group_information + gender + leftright + pol_interest + church_attendance + age + university, data = nb_dat, family = "binomial")

summary(glm_fit)

```



## t_tests

```{r}

## Szenario 1 - Idealism
reg_dat %>% 
  mutate(opinion_change_s1 = ifelse(t1_szenario1q1 == t2_szenario1q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s1, idealism_pca)) +
  geom_violin(aes(fill = opinion_change_s1), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 1 Opinion Change - Idealism")

ggsave(filename = "images/s1_idealism.png", width = 5, height = 5)

## Szenario 1 - Relativism
reg_dat %>% 
  mutate(opinion_change_s1 = ifelse(t1_szenario1q1 == t2_szenario1q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s1, relativism_pca)) +
  geom_violin(aes(fill = opinion_change_s1), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 1 Opinion Change - Relativism")

ggsave(filename = "images/s1_relativism.png", width = 5, height = 5)

## Szenario 2 - Idealism
reg_dat %>% 
  mutate(opinion_change_s2 = ifelse(t1_szenario2q1 == t2_szenario2q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s2, idealism_pca)) +
  geom_violin(aes(fill = opinion_change_s2), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 2 Opinion Change - Idealism")

ggsave(filename = "images/s2_idealism.png", width = 5, height = 5)

## Szenario 2 - Relativism
reg_dat %>% 
  mutate(opinion_change_s2 = ifelse(t1_szenario2q1 == t2_szenario2q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s2, relativism_pca)) +
  geom_violin(aes(fill = opinion_change_s2), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 2 Opinion Change - Relativism")

ggsave(filename = "images/s2_relativism.png", width = 5, height = 5)


### Acquisenz

## Szenario 1 
reg_dat %>% 
  mutate(opinion_change_s1 = ifelse(t1_szenario1q1 == t2_szenario1q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s1, akquisenz_pca)) +
  geom_violin(aes(fill = opinion_change_s1), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 2 Opinion Change - Relativism")

ggsave(filename = "images/s1_akquisenz.png", width = 5, height = 5)

## Szenario 2 
reg_dat %>% 
  mutate(opinion_change_s2 = ifelse(t1_szenario2q1 == t2_szenario2q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s2, akquisenz_pca)) +
  geom_violin(aes(fill = opinion_change_s2), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 2 Opinion Change - Relativism")

ggsave(filename = "images/s2_akquisenz.png", width = 5, height = 5)



### Double Dimension

## Szenario 1
reg_dat %>% 
  mutate(opinion_change_s1 = ifelse(t1_szenario1q1 == t2_szenario1q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s1, ideal_relativ_pca)) +
  geom_violin(aes(fill = opinion_change_s1), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 2 Opinion Change - Relativism")

ggsave(filename = "images/s1_ideal_relativ.png", width = 5, height = 5)

## Szenario 2 
reg_dat %>% 
  mutate(opinion_change_s2 = ifelse(t1_szenario2q1 == t2_szenario2q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(opinion_change_s2, ideal_relativ_pca)) +
  geom_violin(aes(fill = opinion_change_s2), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 2 Opinion Change - Relativism")

ggsave(filename = "images/s2_ideal_relativ.png", width = 5, height = 5)
```

## bivariate

```{r}
reg_dat %>%
  mutate(diff_num = t2_szenario1q2 - t1_szenario1q2) %>% 
  mutate(opinion_change_s1 = ifelse(t1_szenario1q1 == t2_szenario1q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(idealism_pca, diff_num, color = opinion_change_s1)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  ggtitle("Szenario 1 Opinion Change - Idealism")

ggsave(filename = "images/b_s1_idealism.png", width = 5, height = 5)

reg_dat %>%
  mutate(diff_num = t2_szenario1q2 - t1_szenario1q2) %>% 
  mutate(opinion_change_s1 = ifelse(t1_szenario1q1 == t2_szenario1q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(relativism_pca, diff_num, color = opinion_change_s1)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  ggtitle("Szenario 1 Opinion Change - Relativism")

ggsave(filename = "images/b_s1_relativism.png", width = 5, height = 5)


reg_dat %>%
  mutate(diff_num = t2_szenario2q2 - t1_szenario2q2) %>% 
  mutate(opinion_change_s2 = ifelse(t1_szenario2q1 == t2_szenario2q1, 0, 1) %>% as.factor) %>% 
  ggplot(aes(idealism_pca, diff_num, color = opinion_change_s2)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  ggtitle("Szenario 2 Opinion Change - Idealism")

ggsave(filename = "images/b_s2_idealism.png", width = 5, height = 5)


reg_dat %>%
  mutate(diff_num = t2_szenario2q2 - t1_szenario2q2) %>% 
  mutate(opinion_change_s2 = ifelse(t1_szenario2q1 == t2_szenario2q1, 0, 1) %>% as.factor) %>%  
  ggplot(aes(relativism_pca, diff_num, color = opinion_change_s2)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  ggtitle("Szenario 2 Opinion Change - Relativism")

ggsave(filename = "images/b_s2_relativism.png", width = 5, height = 5)

# fit2 <- lm(diff_num ~ t1_szenario1q2 + idealism_pca + relativism_pca, data = reg2)

# sjPlot::plot_model(fit2, show.p = T, show.values = T)

reg_dat %>% 
  mutate(diff_num = t2_szenario1q2 - t1_szenario1q2) %>% 
  select(diff_num) %>% ggplot(aes(diff_num)) + geom_histogram()
  
```



## regression

```{r}
fit1 <- lm(t2_szenario1q2 ~ t1_szenario1q2 + idealism_pca + relativism_pca, data = reg_dat)

sjPlot::plot_model(fit1, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 1") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/reg1.png", width = 5, height = 5)

fit2 <- lm(t2_szenario2q2 ~ t1_szenario2q2 + idealism_pca + relativism_pca, data = reg_dat)

sjPlot::plot_model(fit2, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 2") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/reg2.png", width = 5, height = 5)



fit3 <- lm(t2_szenario1q2 ~ t1_szenario1q2 + akquisenz_pca + ideal_relativ_pca, data = reg_dat)

sjPlot::plot_model(fit3, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 1") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/reg3.png", width = 5, height = 5)

fit4 <- lm(t2_szenario2q2 ~ t1_szenario2q2 + akquisenz_pca + ideal_relativ_pca, data = reg_dat)

sjPlot::plot_model(fit4, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 2") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/reg4.png", width = 5, height = 5)



```

## bayesian regression

```{r}
# devtools::install_github("paul-buerkner/brms", dependencies = TRUE)
pacman::p_load(brms)


brm1 <- brm(t2_szenario1q2 ~ t1_szenario1q2 + akquisenz_pca + ideal_relativ_pca + general_group_discussion + general_group_information, data = reg_dat)

plot_model(brm1, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 1") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm1.png", width = 7, height = 7)

brm2 <- brm(t2_szenario2q2 ~ t1_szenario2q2 + akquisenz_pca + ideal_relativ_pca + general_group_discussion + general_group_information, data = reg_dat)

plot_model(brm2, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 2") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm2.png", width = 7, height = 7)


brm3 <- brm(t2_szenario1q2 ~ t1_szenario1q2 + akquisenz_pca + ideal_relativ_pca + general_group_discussion + general_group_information + akquisenz_pca*general_group_discussion, data = reg_dat)

plot_model(brm3, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 1") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm3.png", width = 7, height = 7)


brm4 <- brm(t2_szenario2q2 ~ t1_szenario2q2 + akquisenz_pca + ideal_relativ_pca + general_group_discussion + general_group_information + akquisenz_pca*general_group_discussion, data = reg_dat)

plot_model(brm4, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 2") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm4.png", width = 7, height = 7)


### full model 

brm5 <- brm(t2_szenario1q2 ~ t1_szenario1q2 + akquisenz_pca + ideal_relativ_pca + general_group_discussion + general_group_information + gender + leftright + pol_interest + church_attendance + age + university, data = reg_dat)

plot_model(brm5, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 1") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm5.png", width = 7, height = 7)


brm6 <- brm(t2_szenario2q2 ~ t1_szenario2q2 + akquisenz_pca + ideal_relativ_pca + general_group_discussion + general_group_information + gender + leftright + pol_interest + church_attendance + age + university, data = reg_dat)

plot_model(brm6, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 2") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm6.png", width = 7, height = 7)

reg_dat %<>% 
  mutate(types = factor(types))

brm7 <- brm(t2_szenario1q2 ~ t1_szenario1q2 + general_group_discussion + general_group_information + gender + leftright + pol_interest + church_attendance + age + university + types, data = reg_dat)

plot_model(brm7, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 1") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm7.png", width = 7, height = 7)

brm8 <- brm(t2_szenario2q2 ~ t1_szenario2q2 + general_group_discussion + general_group_information + gender + leftright + pol_interest + church_attendance + age + university + types, data = reg_dat)

plot_model(brm8, show.p = T, show.values = T) +
  ggtitle("Regression - Opinion Change in Szenario 2") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()

ggsave(filename = "images/brm8.png", width = 7, height = 7)



```






## halfeye

```{r}
# devtools::install_github("mjskay/tidybayes")
pacman::p_load(tidybayes)

# shinystan::launch_shinystan(brm5)
parameters(brm5)


brm5 %>% 
  spread_samples(b_Intercept)


reg_dat %>%
  add_fitted_samples(brm5) -> spread_brm5


spread_brm5 %>% 
  ggplot(aes(akquisenz_pca, estimate, color = .iteration)) +
  geom_halfeyeh()

```



## animate

```{r}
trolley %>% 
  select(general_group_control:general_group_information, 
         t1_szenario1q2, t2_szenario1q2) %>% 
 # spread()
  gather(key, value, -t1_szenario1q2, -t2_szenario1q2) %>% 
  filter(value == 1) %>% #select(key) %>% table()
  mutate(diff = t2_szenario1q2 - t1_szenario1q2) %>% 
  ggplot(aes(key, diff)) +
  geom_col()



trolley %>% 
  select(general_group_control:general_group_information, 
         t1_szenario1q2, t2_szenario1q2) %>% 
 # spread()
  gather(key, value, -t1_szenario1q2, -t2_szenario1q2) %>% 
  filter(value == 1) %>% #select(key) %>% table()
  select(-value) %>% 
  gather(time, support, -key) %>% 
  ggplot(aes(time, support)) +
  geom_violin(aes(fill = time), alpha = 0.4) +
  geom_boxplot(width = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  facet_wrap(~key) +
  stat_compare_means(label.x.npc = "middle", label.y.npc = "top") +
  ggtitle("Szenario 1 Opinion Change - Idealism")

library(gganimate)

trolley %>% 
  select(general_group_control:general_group_information, 
         t1_szenario1q2, t2_szenario1q2) %>% 
 # spread()
  gather(key, value, -t1_szenario1q2, -t2_szenario1q2) %>% 
  filter(value == 1) %>% #select(key) %>% table()
  select(-value) %>% 
  mutate(direction = t2_szenario1q2 - t1_szenario1q2) %>% 
  mutate(direction = case_when(
    direction > 0 ~ "more support",
    direction < 0 ~ "lower support",
    TRUE ~ "same"
  )) %>% 
  gather(time, support, -key, -direction) %>% 
#  filter(time == "t1_szenario1q2") %>% 
  ggplot(aes(key, support, fill = direction)) + 
  geom_violin() +
  transition_states(time, transition_length = 4, state_length = 4) +
  shadow_wake(wake_length = 0.1) +
  ggthemes::theme_hc() +
  ggthemes::scale_color_fivethirtyeight() -> ss

animate(ss, nframes = 30, fps = 10, length = 30)

trolley %>% 
  select(general_group_control:general_group_information, 
         t1_szenario1q2, t2_szenario1q2) %>% 
 # spread()
  gather(key, value, -t1_szenario1q2, -t2_szenario1q2) %>% 
  filter(value == 1) %>% #select(key) %>% table()
  select(-value) %>% 
  gather(time, support, -key) %>% 
  filter(time == "t2_szenario1q2") %>% 
  ggplot(aes(key, support)) + 
  geom_dotplot(binaxis='y', stackdir='center')


trolley %>% 
  select(general_group_control:general_group_information, 
         t1_szenario1q2, t2_szenario1q2) %>% 
 # spread()
  gather(key, value, -t1_szenario1q2, -t2_szenario1q2) %>% 
  filter(value == 1) %>% #select(key) %>% table()
  select(-value) %>% 
  mutate(name = 1:n()) %>% 
  gather(time, support, -key, -name) %>% 
  ggplot(aes(time, support)) + 
     geom_violin(color = "grey70") +
  #    geom_point(aes(group = name, color = factor(name)), alpha = 0.3) +
  #    geom_line(aes(group = name, color = factor(name)), alpha = 0.3) + 
  #    stat_summary(fun.data = "mean_cl_normal", size = 5, geom = "point") +
  #    stat_summary(fun.y = "mean",size = 2, geom = "line", aes(group = 1)) +
  #    ylab("Truth-Pledge Alignment")   +
  #    ggthemes::theme_hc() +
  # ggtitle("Pro Truth-Pledge Alignment  Before & After PTP") +
  # scale_x_discrete("", labels = c("Before PTP","After PTP")) +
  # guides(fill = F, color = F) + 
  stat_compare_means(paired = TRUE, method = "t.test") +
  ylim(1,5)


trolley %>% 
  select(general_group_control:general_group_information, 
         t1_szenario1q2, t2_szenario1q2) %>% 
 # spread()
  gather(key, value, -t1_szenario1q2, -t2_szenario1q2) %>% 
  filter(value == 1) %>% #select(key) %>% table()
  select(-value) %>% 
  mutate(name = 1:n()) %>% 
  gather(time, support, -key, -name) -> ss

# Box plot facetted by "dose"
p <- ggpaired(ss, x = "time", y = "support",
          color = "time", palette = "jco", 
          line.color = "gray", line.size = 0.4,
          facet.by = "key", short.panel.labs = FALSE)
# Use only p.format as label. Remove method name.
p + stat_compare_means(label = "p.format", paired = TRUE)
```










