---
output: pdf_document
---

The discussion about ethical principles can be found today in many socially relevant areas. Research on digital technologies such as autonomous driving, which is already possible and may soon be reality on our streets, must deal with such principles. In Germany, politicians adopted the first set of ethical standards for autonomous driving system manufacturing [cf. @threesixty]. But the question if and how “moral programming” [@birnbacher2016: 9] is possible will be difficult to solve and the political discussion will remain.

Political framing is a phenomenon which is used more and more by politicians today to win people's votes and to convince people for such decisions as mentioned in the example of the autonomous driving. Framing is the setting of frames of interpretation over language and can work in very different ways. Frames are not manipulative per se, but a natural part of all language and one can't resist frames neuronally as they are always activated when we hear or read a word.

In this paper, the ethical decision-making is examined through a survey of action decisions with three different treatment groups regarding the known trolley dilemma and footbridge dilemma. The original dilemma was developed by @foot1978 p. 2 and consists of a mental experiment in which the driver a runaway tram is heading towards a group of five people and will kill these people, unless the tram is diverted to a second track where only one person is standing. The driver has the choice of doing nothing, in which case, five people will perish, or divert the tram, ensuring the death of the person on the other track. This thought scenario is traditionally employed to evaluate deontological and consequentialist reasoning mechanisms [cf. @kahane2015sidetracked: 557].

In this paper we will also consider the gender differences in ethical decision-making, as studies involving trolley dilemmas have found that men are more inclined to make utilitarian decisions than women [cf. @zamzow2009variations: 371]. Research of the past two decades has focussed on these kind of gender differences with regard to moral decisions. However, literature reviewing the interplay between gender and individual ethical positions – and how it influences moral choices – has been “surprisingly scarce” [@donoho2012gender: 57]. This paper will therefore contribute to existing literature by considering the role of ethical positions when explaining gender related patterns in moral decision making.

In the following section, the theoretical background of ethical decision making, ethical positions and the role of gender is examined. In the methodological section the online survey experiment is explained and the operationalization of the variables used in this analysis is discussed. Afterwards, problems regarding the randomization into three treatment groups are analysed and descriptive statistics are reported. What follows is the empirical analysis, for which 12 different models were estimated. In the last section, the results of the analysis are discussed in regard to their broader implications for theory and some concluding remarks on future research are made.
