---
output: pdf_document
---

## Ethical decision making

When faced with an ethical decision, there is rarely a single, indisputable moral course of action. The same action can be considered both moral and immoral. When making such decisions, individuals can refer to certain moral principles, such as “you must not harm”, or “you must not lie”, but can also take into account the consequences of the specific action, these two perspectives consist, respectively, of deontological and teleological decision making logics (2.1.1.). A means of understanding how people make ethical decisions is to use thought experiments such as sacrificial dilemmas like the trolley dilemma, where the individual must choose the action that he/she considers the most moral (2.1.2.).

### Deontological and teleological decision making logics 

In Western normative philosophy, a distinction is traditionally drawn between deontological and teleological ethical frameworks [@singer2013companion]. These perspectives, identified as “the two major ethical principles” by Kohlberg [@kohlberg1984psychology: 579], rely on two distinct bases to assess the morality of acts [@bartels2008principled: 382].
 
Deontology (from “deon”, meaning “duty” or “obligation”) refers to a normative framework in which the morality of an action is judged according to its intrinsic rightness or wrongness irrespective of its consequences [@frankena1973ethics]. The normative principles that determine whether an action is right or wrong are perceived as inherently true without further justification. Kant’s categorical imperative (1785) is considered the key concept of this deontological moral system. It posits that an unconditional rule is considered as a moral end in itself, regardless of the circumstances or purposes [@schwaiger1785kategorische]. It follows that only the moral integrity of the individual act counts. Committing "bad" acts cannot be morally justified, even as a means to morally-imperative ends, and even even if the bad acts are negligible compared to the importance of the larger goal to be achieved (i.e. telling a lie or intentionally harming a person to save millions of lives [@bartels2008principled: 382]).
 
By contrast, teleology (from “telos”, meaning “goal” or “end”) refers to a normative framework in which the morality of an action is solely based on the desirability of the outcome. Here, the moral "goodness" of an action is extrinsic to the action itself, and depends on the consequence of the action [@frankena1973ethics]. Actions are, in a sense, considered morally neutral. Only when taking into account the intended consequence, can an action be morally evaluated. Moral evaluation of an act consists in gauging whether the "goodness" of the outcome overweighs the possible "badness" of the act. Teleological moral reasoning is therefore also referred to as consequentialism. A prominent strand of consequentialist ethics is John Stuart Mill’s utilitarianism, in which actions that ultimately maximise “the greatest good for the greatest number” are judged as moral. [@bartels2008principled: 382]
 
However, these definitions are ideal types. It is commonly assumed that these two categories of ethical reasoning are combinable and that their respective degree is to be nuanced [@cornelissen2013rules:483]. Holmes (1993) differentiates between strong deontology, which does not take into account an act’s "goodness" to determine its rightness, and weak deontology, which sees "goodness" as a major but not decisive factor for moral rightness [@indick2000gender: 286]. As such, the goodness of an act’s consequences is important in both ethical perspectives. It is however the only important element for consequentialism, which aims to produce the best possible outcomes regardless of the means employed. [@bartels2008principled: 382] In certain contexts, deontologist and consequentialist reasoning might lead to the same moral decision, for instance when an intrinsically bad act leads to harmful consequences. In consequentialism, deontological principles are often considered as informal rules which must be overridden in circumstances where not doing so produces harmful consequences (i.e. telling the truth leading to the death of innocent people). [@bartels2008principled: 382]
 
Previous work has shown that this distinction between deontology and teleology is not only relevant in moral philosophy, but also for individuals when reflecting on their actions. Both types of argument can be used to justify actions, and at times both moral reasonings can be combined. Depending on different situations, individuals might focus on one of the two logics or on a combination of both to make their decision. [@cornelissen2013rules:483]

A prominent way of revealing deontological and teleological decision making logics has been to apply them to thought experiments such as the trolley dilemma as well as to its variants in the form of the switch or the footbridge dilemmas.


### Different trolley dilemma settings and different decision making logics

Originally expressed by Foot, what will later be referred to as the trolley dilemma consists of a mental experiment in which a runaway tram is heading towards a group of five people and will kill these people, unless the tram is diverted to a second track where only one person is standing [@foot1967problem: 2]. The individual has the choice of doing nothing, in which case, five people will perish, or divert the tram, ensuring the death of the person on the other track. In this moral dilemma, both inaction and action cannot only be morally justified, but also be considered immoral, depending on the individual’s stance.
 
In the original dilemma, it is the driver of the runaway trolley who must choose to divert the train or not: the “driver […] can only steer from one narrow track on to another; five men are working on one track and one man on the other; anyone on the track he enters is bound to be killed.” The main question in this scenario is “why we should say, without hesitation, that the driver should steer for the less occupied track” [@foot1967problem: 2].
 
In the trolley or switch dilemma, the participating individual is no longer the driver as in the original trolley dilemma, but is a bystander who has the possibility to hit a switch that diverts the trolley from a track heading towards 5 people to a track heading towards one person. There is an accepted morality amongst philosophers that, in this scenario, it might be morally acceptable to hit the switch [@nichols2006moral: 2].
 
The footbridge dilemma refers however to a scenario where a stranger is pushed in front of the trolley to prevent it from killing the five people on the track, by using the body of the stranger to stop the train. Both philosophers and the majority of individuals argue however that it is wrong to push the stranger onto the track, even if this means that the five people will die [@nichols2006moral: 2].
As previous studies have established, “most people think it is permissible to divert a train so that it will kill one innocent person instead of five, but most people think that it is not permissible to push a stranger in front of a train to save five innocents.” [@nichols2006moral: 1].
 
Given the similarity of the outcome of these scenarios, where one person is sacrificed to save 5, and the differing responses, this result seems interesting. It has been argued that people are more inclined to apply a teleological logic when it comes to the trolley dilemma and a deontologist logic when solving the footbridge dilemma [@nakamura2013closer: 803].
 
Where do these different decision making logics stem from? Let us recall that for consequentialists the relevant unit of analysis is the outcome and not the action whereas for deontologists, the opposite holds true. This is the reason why especially deontologist philosophers have developed a set of different trolley scenarios that evoke intuitive reactions in favour of the normative assumption that certain acts are impermissible. By designing cases similar to the footbridge dilemma, deontologists emphasise that some actions are so “evil” that consequentialism is not an appropriate moral theory to justify them. [@bartels2008principled: 385] Using these different scenarios, they argue that actions leading to similar outcomes can present different type of actions and therefore trigger different moral judgements. For instance, the act of killing can be seen as forbidden whereas the decision to let somebody die might be morally justifiable [@bartels2008principled: 385].
 
Within the field of moral philosophy, the type of intention is central to determine the morality of a specific action [@foot1967problem: 2]. As Foot explains, the difference can be drawn between ““what we allow” (thought of as obliquely intended) and “what we do” (equated with direct intention)[@foot1967problem: 3]. There is an obvious difference between a situation where the intention to kill is direct, and a situation where death is the consequence but not the purpose of a decision. The intention to kill is thus oblique, that is to say, a natural and foreseeable consequence of switching the track, but not the main intention. If the intention of the push is to kill the pushed individual, i.e. that the individual must die in order to save the others, then death is a direct intention. Whereas in the case of switching the track, the death caused is an oblique intention. The switch dilemma is thus usually considered as an “incidental” dilemma, in which the death of one person is a predictable but not intended result of the action aimed at saving more people. The footbridge dilemma, on the other hand, belongs to the category of “instrumental” dilemmas, in which the killing of one person is an absolute necessary means to save more people. [@lotto2014new: 1] As Greene sums up, “[…] the difference between these two cases lies in the fact that in the footbridge dilemma one literally uses a fellow human being as a means to some independent end, whereas in the trolley dilemma the unfortunate person just happens to be in the way” [@greene2001fmri: 2105].
 
Another aspect to be taken into account is the degree of personal involvement. When confronted with an “impersonal” dilemma like the switch scenario (diverting the trolley away from five people to one person), which does not elicit emotional reactions, most respondents engage in a consequentialist logic, whereby it would be morally acceptable to let one person die to save more people. However, when dealing with a “personal” dilemma like the footbridge scenario (pushing a person onto the tracks so that the person’s body stops the trolley from reaching five people), emotional reactions are elicited and most people refuse to commit a harmful act, thereby engaging in a deontological logic. [@gleichgerrcht2013low: 1] It has been established that the degree of emotions involved might increase when the intention to harm is combined with the use of personal force. In addition, the use of personal physical force also influences the perceived morality of an action. This involves physically pushing someone into harm’s way, rather than pulling a trigger on a gun for example. A situation in which personal force is exerted will thus be considered morally worse than if a switch is flicked [@greene2001fmri: 2105]. Previous studies have shown that this kind of scenario evokes the strongest emotional reaction and consequently a more deontology-consistent response. [@gleichgerrcht2013low: 1]
 
Whilst appearing to be fundamentally similar in their outcomes, the differing actions employed in these two dilemmas appeal to different ethical decision making logics, thus making these dilemmas highly adapted to analysing the different influences of ethical positions and their different interactions with gender and deliberation processes. These are elements that will be explored in the following chapters.

## Ethical Positions

Current theoretical approaches believe that „individual differences in ethical ideology […] play a key role in ethical decision making.” [@davis2001measuring: 35]. This means that each individual’s moral philosophy may have an influence on a person’s ethical judgments, his or her response and behavior in a given situation.
A way of classifying these different moral philosophies is proposed by Forsyth (1980, 1992) and involves two dimensions; relativism and idealism. According to Forsyth, moral judgments and decision making will vary according to one’s position on these two dimensions [@davis2001measuring: 35]. These “individual moral beliefs and attitudes are part of an integrated conceptual system of personal ethics” [@davis2001measuring: 35].

The first concept, idealism, "refers to individuals' concern for the welfare of others” [@forsyth1988idealism: 244]. Those individuals who are idealistic in their moral judgements (“idealists”), “believe in the absolute value of ethical standards based on unselfish concern for others” [@park2005role: 84]. Therefore their ethical judgment are “morally absolute in terms of moral principles, norms or laws” [@park2005role: 83] insisting that one must always avoid harming others and act for the welfare of others [cf. @forsyth1988idealism: 244]. Avoiding harming others can thus be perceived as a universal principle that can under no circumstances be broken. In contrast, non-idealistic individuals may approve harming someone, which “will sometimes be necessary to produce good" [@forsyth1988idealism: 244]. Idealism has been found to positively influence “the degree of deontological norms and ethical judgment (Vitell et al., 1993), perceived importance of ethics and social responsibility (Etheredge, 1999; Singhapakdi et al., 1996b), and ethical judgment and behavioral intention (Marta et al., 2001; Singhapakdi et al., 1996b, 1999).” [in @park2005role: 84].

The second concept, relativism, “refers to the extent to which individuals base their personal moral philosophies on universal ethical rules” [@forsyth1988idealism: 244]. Those individuals who are relativistic in their moral beliefs (“Relativists”), see all “moral standards are relative to a society and culture” [@park2005role: 83]. They assume that exceptionless moral principles do not exist [cf. @forsyth1988idealism: 244] and that moral actions depend on the situations and circumstances [cf. @park2005role: 83]. Ethical Decision Making of what is morally right and wrong can be changed according to the situation [cf. @park2005role: 84]. On the other side, non-relativists see certain principles as their “guidelines for action” [@forsyth1988idealism: 244].

The major contribution that Forsyth made was to emphasize that idealism and relativism are not mutually exclusive dimensions, as previously assumed. [@davis2001measuring: 35] This means that both traits can be combined. An individual who exhibits a high degree of both idealist and relativist traits might be idealist when certain principles are concerned (i.e. “under no circumstance one can violate individual human rights”) while being relativist in other domains (i.e. “whether it is morally right to divorce depends on the sociocultural situation”).

Since these two concepts are considered independent, Forsyth distinguishes between 4 subtypes, depending on the varying degree to which an individual might exhibit idealist and/or relativist characteristics; Absolutists (high idealism/low relativism), Subjectivists (high relativism/low idealism), Situationists (high idealism/high relativism) and Exceptionalists (low relativism/low idealism) [cf. @Strack2007erfahrung: 1].

Whereas Forsyth (1992) sees the dimensions, idealism and relativism, as independent concepts of belief, many researchers have found contrasting relationships of idealism and relativism with ethical constructs [cf. Etheredge, 1999; Marta et al., 2001; Singhapakdi et al., 1996b, 1999; Vitell et al., 1993 in @park2005role: 84]. Because of problems associated with their compatibility or the juxtaposition/contrasting of relativism and idealism, the four subtypes have been criticized in the literature, [cf. @strack2007erfahrung: 2; @park2005role: 849], this study concentrates therefore on the first two subtypes, which are the absolutists (as referred to be highly idealistic) and the subjectivists (as referred to be highly relativist).

Given the characteristics of these two concepts as mentioned above, links can be drawn with deontological and consequentialist decisions. More idealistic individualsIdealists  accentuate the importance of not harming others at any cost, thus deontological reasoning dominates the decision making process. We can thus formulate the following hypothesis:

> H1a: The more idealist an individual, the less likely he/she will switch/push

Persons with high relativismRelativists however recognize that rules are not universal and can be broken, thus other factors may influence the decision process, including the consequences of action and inaction in addition to rules such as not to harm. Given therefore that relativism can both lead to action and inaction in the case of the trolley dilemma, the following hypothesis has been formulated:

> H1b: Relativism has no effect on an individual’s decision to switch/push

## The Influence of Gender

Gender, be it due to biological or sociological causes, is strongly associated with influencing an individual's values, ideals and priorities. This is particularly visible in the case of moral decision-making where the decision is based almost purely on these three factors. Thus, gender will influence whether an individual is more likely to make deontological or consequentialist ethical decisions (2.3.1.). Given these tendencies, gender is therefore associated to an individual's ethical position (2.3.2.)

### Gender and Ethical Decision Making

As Marta and colleagues pointed out, “gender is regularly identified as a particularly important personal characteristic, which may affect ethical decisions“. [@marta2008personal: 593] The claim that gender decisively influences choices when it comes to ethical issues has been empirically established [@glover2002: 223f.]. While both men and women consider their moral standards as higher than the other gender, the ethical judgements of men are less empathetic and sensitive than those of women [@donoho2012gender: 57]. Explanations for this gender difference is diverse, with two main strands of theorizing standing out. 

One is the trait-driven account, which contrasts male instrumentalism and high competitiveness against female empathy and sensitivity [@donoho2012gender: 57]. Behavioral endocrinology maintains that biological aspects, for instance the higher level of testosterone in men, may influence their ethical decisions. Testosterone is related to increased risk tolerance and higher endurance of conflict, fear, stress and threats. At the same time, it impedes reaction to affective signals, which plays an important role in encouraging empathic behaviors and choices. Carney and Mason therefore assumed that “individuals high in testosterone are more likely to make utilitarian decisions—specifically when doing so involves acts of aggression and social cost.” [@carney2010decision: 668]

An alternative account for these differences is gender socialization theory, which assumes that different orientations between men and women are the result of divergent socialization experiences more than that of innate biological traits [@donoho2012gender: 57]. This theory can be traced back to Freud (1925) and Piaget (1932), and was applied by Gilligan (1982) to explain the gender difference in moral evaluation logics. Individuals are expected from their early childhood to act according to gender related stereotypes, leading men and women to develop different thinking processes and, as a consequent, different behavioral patterns [@dubinsky2005consumers: 1693]. Thereafter, men are socially rewarded for exhibiting competitive behaviors whereas women are expected to exhibit caring, nurturing behaviors [@donoho2012gender: 57].

In her work, Gilligan (1982) focused especially on the reasoning in moral dilemmas, and emphasizes that an important, often neglected factor in moral decision-making is the “care” component. She criticizes the focus of traditional theories, both in philosophical ethics and in moral psychology, on the criteria of justice and fairness as a primary determinant of human moral evaluation. She suggests that care is a decisive factor that sets apart male and female psychology when it comes to moral issues. A justice orientation is characterized by logic and reason, whereby moral decisions are made based on impartiality, and can be applied to every situation regardless of the circumstances to derive an ultimate “just” decision. A care orientation is motivated by empathy, and moral decisions can involve subjective emotions and individual evaluation of the respective relationships and situations. While these two orientations are not mutually exclusive, Galligan assumes that men are more likely to prioritize principles of justice over the principles of care, whereas it is the opposite for women. The takeaway from this theory is that the “ethic of justice”,  that frequently leads to consequential and objective moral evaluation, tends to  characterize the male moral decision-making logic, while the “ethic of care”, which often leads to the consideration of individual circumstances and motivations, is more indicative of female moral reasoning. [@carol1982different: 25 pp.]

Traits and socialization together provide theoretical reasons to believe that moral evaluation patterns differ between gender, with men being more inclined to make consequentialism-consistent decisions, while women being more inclined to make deontology-consistent decisions. As Dawson (1992:24) describes, women evaluate moral behavior “by a standard of inclusion and an injunction against hurting others” [in @ harris2004gender: 193] – a behavior that corresponds with the decision to not switch or push when confronted with the Trolley dilemma. This leaves us with the following hypothesis:

> H2a: women are less inclined to switch/push than men.

### Gender and Ethical Positions

While this conclusion might be plausible, Walker’s (1984) meta-analysis of 108 studies has also shown contradicting results, with only 8 cases clearly indicating gender differences in moral decision making [in @indick2000gender: 287]. It is therefore legitimate to assume that, while gender-generated preferences do account for moral reasoning and moral choices to some extent, other factors decisively intervene to modify this relationship. This brings us back to ethical positions, assumed to be a key influencer of moral decisions in this paper. We will consider the role of ethical positions when explaining gender related patterns in moral decision making.

One of the few who explored the relationship between gender and ethical positions is Schminke (1997), with findings indicating that both men and women slant towards relativistic frameworks. [@schminke1997effect] Differences become apparent however when distinguishing between contexts: when it comes to decisions in non-business settings, women exhibit more idealism, while men exhibit more relativism [@donoho2012gender: 57].

So how does an individual’s moral decision concerning the Trolley dilemma change when its gender generated preferences for either deontologist or consequentialist orientation meet the influence of its idealism and relativism?

With regard to idealism, we can maintain that a high degree of this trait makes an individual adhere to the cardinal rule of never actively harming another human beings [@forsyth1988idealism: 244], hence making it opt for a deontological decision when confronted with the Trolley Dilemma. We just assumed that gender is indicative of differences in moral choices. However, it is plausible to assume that gender becomes increasingly irrelevant to predict an individual’s moral choice the more it is characterized by this trait. However strongly a man (or a woman, in some cases) might have been socialized to endorse consequentialist-driven decisions, his reluctance to actively harm a person will become stronger the more idealist he is. This leaves us with the following hypotheses:

> H2b: The more idealist a woman, the less inclined she is to switching/pushing

> H2c: The more idealist a man, the less inclined he is to switching/pushing

> H2d: The difference between woman and men (see H1) becomes smaller with higher idealism.
 
On the other hand, relativism is defined as the extent to which individuals reject universal ethical principles as the foundation for their moral philosophies. A high degree of relativism makes an individual evaluate morality on a case to case basis, making its moral judgements independent from sociocultural contexts [@park2005role: 83] – including gender-generated patterns of thinking. We can therefore assume that, with increasing levels of relativism, a man or a woman’s initial gender-related preferences for either deontology- or consequentialism-orientated choices, still exist, but become increasingly moderated by relativist scrutinization. The latter requires that the individual includes alternative principles and considerations when making moral evaluations. However strongly an individual might have been socialized to follow a certain decision making logic because of its gender, with increased relativism, it will be more inclined to reject the decision making logic that has been ascribed to it because of gender socialization.

While women are initially more likely to give a deontology-consistent response compared to their male counterpart (because of their care-orientation), their behaviour might deviate from this by gender generated reference framework the more relativist they are. This leaves us with the following hypothesis:

> H2e: The more relativist a woman, the more inclined she is to switch/push
 
Conversely, while men are initially more likely to give a consequentialism-consistent response compared to their female counterpart (because of their justice-orientation), their behaviour might deviate from this by gender generated reference framework the more relativist they are. This leaves us with the following hypothesis:

> H2f: The more relativist a man, the less inclined he is to switch/push


## The Influence of Deliberation
 
### Definition of Deliberation

To give a definition of deliberation, one needs to take a closer look at the idea of deliberative democracy as there exists no single definition of deliberation. Many theorists thus focus on the essential features of deliberative democracy to define the concept.

This form of democracy “sees preference formation as a public, interpersonal activity at the core of democracy rather than an exogenous and private process that precedes political choice” [@leeper2017deliberation: 1]. Jürgen Habermas, one of the main contributors to deliberative theory, developed a model of deliberation. This model is defined through the logic of communicative action through common understanding  [@habermas1982theorie: 385].

Deliberation is “not concerned with the aggregation of pre-existing, fixed preferences” but can be described as a “process in which political actors listen to each other, reasonably justify their positions, show mutual respect, and are willing to re-evaluate and eventually revise their initial preferences” [@steenbergen2003measuring: 21].

Myers and Mendelberg [in @huddy2013oxford: 701] define deliberation as “the free, open-minded dialogue about a matter of public concern among anyone affected by the issue.” Thus, we can say that deliberation is a form of dialogue between citizens who often already have a position regarding the topic at hand.
 
### Deliberation and Ethical Decision Making
 
An assumption about how deliberation might influence moral decisions was formulated by Kahane [@kahane2015sidetracked: 557], who argues that “deliberative processing is needed to weigh competing moral rules, not to perform a utilitarian cost–benefit analysis”.  He interprets deliberative platforms as a place to discuss competing deontological guidelines, such as the « particularly salient deontological principle telling us that we mustn’t cause certain kinds of harm (a component of what is often known as the duty of non-maleficence), and an opposing duty to prevent grievous harm to others (a component of beneficence) » [@kahane2015sidetracked: 557]. The idea here is that the deliberation process consistently encourages emotional, deontology-consistent moral reasoning rather than consequentialist cost-benefit calculations that is less intuitive and more effort-intensive. The implication here is that people are more likely to slant towards deontology-consistent behaviour after being subjected to deliberative influences.
However, other authors examining the link between deliberation and decision making concerning moral issues have come to the opposite conclusion despite starting from the same point of reference. Greene et al. also assume that deontology-consistent judgements are mainly produced by emotional responses while consequentialist-consistent judgements are the result of factual reasoning” [@greene2008secret: 35 f.]. While Kahane and like-minded authors conclude that deliberative action favours intuitive, deontological reasoning when moral issues are concerned, Greene et al. argue that deliberation serves rather as a platform that allows deontological intuitions to be overshadowed by consequentialist reasoning [@greene2008secret: 35 f.]. Thus, consequentialist moral judgments are generated by deliberatively arguing away initially predominant, deontology-orientated intuitions.

As these are two opposite views on the potential effect of deliberation on moral decision making logics, no clear theoretical conclusion can be drawn. However, we might resolve this mystery by taking into the equation the interaction between individual ethical dispositions and deliberation processes. As mentioned before, idealist individuals show a high degree of adherence to universal principles, while relativist individuals show a high degree of rejection of universal principles. Given this key difference between relativism and idealism, it is interesting to compare the effect of idealism and that of relativism on ethical decision making logics when deliberation as an intervening variable comes into play. The main question here is then, which kind of moral decision making logic individuals follow when idealist traits or relativist traits are combined with deliberation.

In this paper, we assume that the deontology-favouring effect of deliberation, as outlined by Kahane, does not apply to all individuals alike, but mainly to those already exhibiting idealist traits. Relativists, on the other hand, are less predictable with regard to the influence that deliberation has on their moral decisions. They are open to all kinds of deliberative influences, those that favour deontology consistent responses, and those that favour consequentialist consistent responses. However, if the consequentialist-favouring effect of deliberation, as explained by Green et al. does indeed apply, then it is more probable that this logic only works on individuals with relativist traits and not on those with idealist traits. We will derive hypotheses following these three lines of reasoning to test which out of these are salient.

First of all, individuals with idealist characteristics rely strongly on universal principles as a moral guideline, implying that these individuals are more likely to “jump onto” whatever argument that may support their position while ignoring opposite views.  They will shy away from making the effort of developing exhaustive cost-benefit analyses that is counterintuitive and that requires them to distance themselves from their familiar way of thinking. Furthermore, it has been theorized that deliberation, when involving people with firm preferences, might lead to making their initial opinions more extreme instead of changing their opinions [@schkade2010deliberation: 1]. Following this logic, we assume that idealist individuals, who already adhere to the cardinal rule of “not harming”, are likely to consolidate their initial position after a being confronted with opposing arguments. As they have always relied on their cherished principles to guide and to justify their behaviors, it is important for them to defend these even more strongly when challenged by non-likeminded people. Being backed-up by peers in the same camp, individuals possessing rigid, untouchable principles tend to consolidate rather than reconsider their position after a discussion. So, we evolved the following two hypotheses:

> H3a: Receiving supporting and opposing arguments strengthens the effect of idealism on decision to not switch/push (Assuming H1a validated, this means that idealist individuals will be even less likely to switch/push after being given arguments in favour and against the deontological decision)

> H3b: Discussion supporting and opposing arguments strengthens the effect of idealism on decision to not switch/push (Assuming H1a validated, this means that idealist individuals will be even less likely to switch/push after discussing the arguments in favour and against the deontological decision)

Relativists, on the other hand, reject the claim that moral values and principles are set in stone. To take an example, moral relativism is the claim that the truth or justification of beliefs with moral content is relative to specific moral codes (which in turn might depend on/co-vary with underlying paradigms, cultures, belief systems or linguistic contexts). Thus, relativists are more susceptible to outside influences. They are therefore more likely to change their opinion when receiving new information that challenges their initial view. Summing up, idealists are more likely to consolidate their position when challenged by new ideas and when having to defend their universal principles in discussions, while individuals with high relativism, who tend to reject of irrefutable universal truths, are probably more open to deliberative influences that might lead to opinion change, but not in a specifically predictable direction. This leaves us with the following hypothesis:

> H4a: In general, relativism has no effect on the direction of opinion change.
 
Lastly, if we take into account Green et al.’s argument – that deliberation allows for consequentialist-rationalist reasoning to overshadow initially deontology-consistent responses in moral arguments – then we can assume a hypothesis that is contrary to H4a. In this case, we would assume that deliberation does influence the direction of opinion change in favour of derailing the trolley or of pushing the person to be save five other people. While this logic might not apply to idealist individuals (who tend to be unwavering when their moral principles are concerned), it might kick in when relativist individuals (moral principles relative to individual context) are persuaded by those utilitarian cost-benefit analysis during the deliberative process. This leads us to an additional hypothesis to be tested against H4a:

> H4b: After experiencing deliberative influences, the more relativist an individual is, the greater the opinion change in the direction of switching/pushing.


