---
output: pdf_document
---

In this section, the results are discussed in regard to their theoretical implications. It ends with some concluding remarks on limitations of this study and recommendations for further research. The conducted analyses of data from the online survey experiment indicate rather strong support for a negative effect of idealism and  no effect of relativism on moral decision making, which is in line with the theoretical assumptions. Moreover, gender has shown to be a reliable predictor, with women finding it less justifiable to switch track/push a person, which is in line with reported gender-differences in moral judgements  from previous studies [cf. @zamzow2009variations: 371]. In addition, the theoretically proposed interaction effects between gender and idealism/relativism were empirically confirmed, although the evidence was in sum rather weak. One theoretical explanation could be, that women are more care-oriented than men, and therefore are more conscious of the moral implications for both scenarios, while men become more care-oriented when their personal involvement is concerned. Idealism has a similar effect for both women and men, although the effect is stronger for men, resulting in almost no observable differences between genders at high levels of idealism. Regarding relativism, a positive effect for women can be observed, especially for scenario 1, but also for scenario 2. This is in line with the assumption that the more relativist a woman, the more likely it is that she will switch/push. Men in turn are less inclined to finding it morally justifiable to switch tracks with higher relativism, while for the push person scenario, relativism has only a very weak effect in this direction. This is mainly in line with the assumption that the more relativist a man, the less likely it is that he will switch/push.

Discussion and information treatment on their own seem to have an effect in the direction of finding it less justifiable to switch/push after receiving the respective treatment, but the effect of idealism is not influenced by those treatments. The theoretical assumptions regarding treatment-effects on idealisms relationship with opinion change are therefore not confirmed. Regarding this hypotheses, the effects did not point in a clear direction. For individuals in the information group, idealism had no effect, while the control and the discussion group showed slightly divergent and negative idealism-effects.

Regarding the two contradictory hypotheses concerning relativism, for the first hypothesis that relativism has no effect on the direction of opinion change, only weak support can be found, as mostly rather small effects can be observed. The ones that can be observed point in the direction of opinion change towards finding switching/pushing less justifiable when receiving information and discussion treatments, when being an individual with high relativism. This finding contradicts the second hypothesis about relativism, that for the discussion group, relativism would have an effect on opinion change in the direction of more utilitarian decisions.

One important finding of this analysis is, that  the results for scenario 1 and scenario 2 are often not in line. One theoretical explanation could be the different framing of the dilemmata. As discussed in the theoretical part of this work, the second scenario consists of a person being a means to stop the waggon, while in the switch track scenario the person is just standing in the way. Moreover, a rather impersonal act is used in the switch track scenario, while pushing someone in front of a train consists of a personal action. Therefore, the push person scenario typically elicits more emotional reactions, which result in less utilitarian judgements. The fact that the effect of idealism is stronger for scenario 2 can be explained by the more ‘direct’ or extreme character of the hypothetical situation in which respondents were asked to make a decision. In regard to the finding that the difference between men and women is stronger for scenario 1 than scenario 2, the more emotional reactions could be an explanation. The same holds true for the weaker positive effect of relativism for women in the push person scenario, compared to the switch track scenario. In the former, the personal involvement and resulting emotional reactions could have weakened the effect of relativism for women, which are more care-oriented and have a greater tendency to emotional reactions. In regard to the finding, that relativism has a strong effect in the direction of finding it less justifiable to switch tracks in general, it appears that perceptions of  moral justifiability of  pushing a persons is less influenced by gender, relativism and the interaction of both than the perceptions for switching track. Especially idealism on its own seems to be a stronger predictor when it comes to pushing a person, for which it has a stronger effect than for the switch tracks scenario.  For the switch track scenario, the situation seems to be judged more ambivalent, which is why relativism and gender become more relevant, which is a hypothesis future research could examine in depth. Regarding the effects of the different treatments on the relationships between idealism and relativism and the dependent variable opinion change, no such possible framing effects can be observed. The results for both dilemmas are mostly in line. Summing up, framing (switching vs. pushing) appears to have an effect, although not consistently. Especially the effect of gender on moral judgements seems to be influenced by the framing of the judged scenario, while relativism appears to be more important when idealism is less influential.

The findings of this study should be interpreted with caution, as there are some limitations, which will be shortly outlined here. Firstly,  no random sample was conducted and the selection process was highly skewed (see section 2). Therefore the representativity of the results can not be assumed. Moreover, the study includes not more than 300 individuals and is therefore based on a small sample. A greater drawback is though, that the randomization into the treatment groups has  failed to some degree as there are significant differences between the groups regarding variables central to this analysis: gender,  relativism and the dependent variables. Therefore, the results of this analysis should be used cautiously and need to be validated by further research. 

Finally, this study has also some general implications for further research regarding the relationship of gender and the ethical positions relativism and idealism with moral decision making. First, gender has shown to be an important determinant which should be included in future studies. Further, the framing of the problem (personal vs. impersonal) seems to be influential, especially regarding effects of gender. Also, both information and discussion have shown to influence opinion change regarding such dilemmata towards more deontological/less utilitarian judgements. All of these effects should not be neglected in future studies on ethical decision making. 
